services:
  caddy:
    environment:
      SERVER_URL: ${SERVER_URL}
      SERVER_CONTAINER_NAME: ${SERVER_CONTAINER_NAME}
      SERVER_PORT: ${SERVER_PORT}
    image: caddy:alpine
    ports: ['${SERVER_PORT}:${SERVER_PORT}']
    volumes: [./Caddyfile:/etc/caddy/Caddyfile]
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        caddy fmt --overwrite /etc/caddy/Caddyfile
        caddy run --config /etc/caddy/Caddyfile --adapter caddyfile

  server:
    environment:
      SERVER_PORT: ${SERVER_PORT}
    container_name: ${SERVER_CONTAINER_NAME}
    build: ./
    depends_on:
      caddy:
        condition: service_started
