services:
  caddy:
    environment:
      BACKEND_URL: ${BACKEND_URL}
      BACKEND_CONTAINER_NAME: ${BACKEND_CONTAINER_NAME}
      BACKEND_PORT: ${BACKEND_PORT}
    image: caddy:alpine
    ports: ['${BACKEND_PORT}:${BACKEND_PORT}']
    volumes: [./Caddyfile:/etc/caddy/Caddyfile]
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        caddy fmt --overwrite /etc/caddy/Caddyfile
        caddy run --config /etc/caddy/Caddyfile --adapter caddyfile

  backend:
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
    container_name: ${BACKEND_CONTAINER_NAME}
    build: ./
    depends_on:
      caddy:
        condition: service_started
